#!/usr/bin/env node

var toMarkdown = require('to-pure-markdown')
var sanitize = require('sanitize-html')
var striptags = require('strip-tags')
var he = require('he')

var remove = ['link', 'script', 'style']
var allowed = ['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'blockquote',
  'p', 'a', 'ul', 'ol', 'quote', 'q', 'img',
  'form', 'textarea', 'input', 'select', 'option', 'button',
  'nl', 'li', 'b', 'i', 'strong', 'em', 'strike', 'code', 'hr',
  'caption', 'pre']

var stripped = striptags(process.argv[2], remove)
var md = toMarkdown(stripped, {allowedTags: allowed})
var decoded = he.decode(md)
var sanitized = sanitize(decoded)

process.stdout.write(sanitized)
