#!/usr/bin/env node

var addressparser = require('addressparser')

function parse (initial) {
  var addresses = addressparser(initial)
  if (addresses.length) {
    if (addresses[0].address) {
      return addresses[0].address
    } else {
      return initial
    }
  } else {
    return initial
  }
}

process.stdout.write(parse(process.argv[2]))
