#!/usr/bin/env python3

from urllib.parse import urlparse
import os, sys

u = urlparse(os.environ['GRAPHSTORY_URL'])

os.system('cycli -h {host} -P {port} -p {password} -u {username} -s -r'.format(host=u.netloc.split('@')[1].split(':')[0], username=u.username, password=u.password, port=u.port, ssl=True, read_only=True))
