#!/usr/bin/env node

var Paypal = require('paypal-recurring2')

var paypal = new Paypal({
  username: process.env.PAYPAL_API_NAME,
  password: process.env.PAYPAL_API_PASSWORD,
  signature: process.env.PAYPAL_API_SIGNATURE
}, process.env.PAYPAL_PRODUCTION === "true")

var t = setTimeout(function () {}, 2000)
var arg = JSON.parse(process.argv[2])

paypal.authenticate(arg, function (err, data, url) {
  if (err) {
    process.stdout.write(err)
    process.exit(1)
  }
  process.stdout.write(url)
  clearTimeout(t)
})
