#!/usr/bin/env node

var Paypal = require('paypal-recurring2')
var getStdin = require('get-stdin')

var paypal = new Paypal({
  username: settings.PAYPAL_API_NAME,
  password: settings.PAYPAL_API_PASSWORD,
  signature: settings.PAYPAL_API_SIGNATURE
})

getStdin().then(function () {
  paypal.createSubscription(token, PayerID, {
    AMT: 10,
    DESC: 'boardthreads.com subscription for user ' + ,
    BILLINGPERIOD: 'Month',
    BILLINGFREQUENCY: 1,
    MAXFAILEDPAYMENTS: 3,
    AUTOBILLOUTAMT: 'AddToNextBilling',
  }, function (err, data) {

  })
})
