#!/usr/bin/env node

var Paypal = require('paypal-recurring2')

var paypal = new Paypal({
  username: process.env.PAYPAL_API_NAME,
  password: process.env.PAYPAL_API_PASSWORD,
  signature: process.env.PAYPAL_API_SIGNATURE
}, process.env.PAYPAL_PRODUCTION === "true")

var t = setTimeout(function () {}, 2000)

var token = process.argv[2]
var PayerID = process.argv[3]
var arg = JSON.parse(process.argv[4])

paypal.createSubscription(token, PayerID, arg, function (err, data) {
  if (err) {
    process.stdout.write(err)
    process.exit(1)
  }
  process.stdout.write(data.PROFILEID)
  clearTimeout(t)
})
