#!/usr/bin/env node

var Paypal = require('paypal-recurring2')

var paypal = new Paypal({
  username: process.env.PAYPAL_API_NAME,
  password: process.env.PAYPAL_API_PASSWORD,
  signature: process.env.PAYPAL_API_SIGNATURE
}, process.env.PAYPAL_PRODUCTION === "true")

var t = setTimeout(function () {}, 2000)
var profileId = process.argv[2]

paypal.modifySubscription(profileId, 'Cancel', 'User-triggered.', function (err, data) {
  if (err) {
    process.stdout.write(err)
    process.exit(1)
  }
  clearTimeout(t)
})
